env: flex
runtime: nodejs

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
  
env_variables:
  SQL_USER: root
  SQL_PASSWORD: passwd
  SQL_DATABASE: project
  # e.g. my-awesome-project:us-central1:my-cloud-sql-instance
  INSTANCE_CONNECTION_NAME: metrepp:europe-west1:metrepp

beta_settings:
    cloud_sql_instances: metrepp:europe-west1:metrepp